# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Colin Bull'
tagline:          'Functional .NET, F#, C#'
description:      ''
url:              http://colinbull.github.io
baseurl:          /

author:
  name:           'Colin Bull'
  url:            https://twitter.com/colinbul

paginate:         5

github:
  repo:           https://github.com/colinbul/colinbull.github.io
